apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  clusterIP: None
  ports:
    - port: 9042
  selector:
    app: cassandra
